import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Categories from "@/components/categories/Categories";
import Hero from "@/components/hero/Hero";
import CategoriaMobile from "@/components/categories/CategoriaMobile";
import CustomProvider from "./redux/CustomProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          <Navbar />
          <Categories/>
          {children}
        </CustomProvider>

      </body>
    </html>
  );
}
